### ISSUE TITLE
Allow Filename Convention Option and Sanitize Title

### ISSUE THREAD

**Issue by dredhorse** [kaiiiz/obsidian-raindrop-highlights-plugin#18]
Hi,
would be nice if we would be able to choose a specific Filename Convention.

At the moment I try to rename the file via Templater, which requires me to sanitize the title by myself with https://gist.github.com/barbietunnie/7bc6d48a424446c44ff4
You use your own code to do that for the filename, but it is not available for the title directly.

**Comment by robertandrews** [comment]
What kind of alternative naming convention are you aiming for besides title?
Is this about sanitising any characters which may not be allowed in file names?

**Comment by dredhorse** [comment]
My general approach for naming all my resource material (unprocessed) ist to let the title start with SM -  (SM = Source Material)
My own notes about those (a destilled note of the contents) start then normally without the SM. e.g.
"SM-Some Nice Resource Name"
"Some Nice Resource Name"

As I only use this plugin at the moment for putting my "Bookmarks" into Obsidian (as I push the Highlihgts via Readwise) I would like to give the name directly the Bookmark identifier of §.
There is no real need anymore to rename them because I already due the processing already in Raindrop before I move those "Bookmarks" into the "Bookmark Collection", which is the only collection I sync.

The plugin also does filename sanitising by itself for the names coming from Raindrop.

**Comment by robertandrews** [comment]
> My general approach for naming all my resource material (unprocessed) ist to let the title start with SM - (SM = Source Material) My own notes about those (a destilled note of the contents) start then normally without the SM. e.g. "SM-Some Nice Resource Name" "Some Nice Resource Name"

Very interesting. I am nerdishly fascinated to learn more about / see an example of this.

You sound like a Zettelkasten-type PKM practitioner. I am aware that the usual discipline is to write notes about a source material _in your own words_ (and whether you can that a "Literature Note" etc, I frequently get caught up in).

Do your "SM- Some Nice Resource Name" files remain in situ, but you drop the "SM" when you have added your own distilled notes? Or are you saying you keep both files, with your writing pointing to the source?

Feels to me like my distillation writing would probably go alongside the highlights/notes themselves, and maybe even that notes taken in Raindrop *are* my distilled writing.

But I have started to wonder about keeping the *whole* of a bookmarked article. This would really encapsulate "Source Material" as a distinct document from the distilled-takeaways note that would refer to it. I filed issue #25. This would also represent keeping a local copy of material, since web articles can disappear. I am speculating that keeping the full text and a separate distillation would actually accentuate the discipline's distinction between these two parts of the practice.

**Comment by lukemt** [comment]
I was also trying to prefix the imports with "Bookmark - " so I don't confuse them and I'd be able filter them with the QuickSwitcher. Also I found out that the Obsidian search algorithm prioritises small file names - and I don't want to prioritise bookmarks for that matter.

**Comment by lukebarton** [comment]
I also wish to customise the filenames. I actually don't want the files to be in their 'Collections' folders. There are plenty of plugins that create files that give users full control over the naming of the files/directory structure -- Periodic Notes is one example of this you may take inspiration from.

**Comment by freshgruts** [comment]
Yes, please… Having some control over the filename would be nice—as would being able to send all imports to the same folder, irrespective of which Raindrop collection they're in. (Fantastically useful plugin, BTW. Thanks)

**Comment by kaiiiz** [comment]
Implemented in 0.0.17.
