### ISSUE TITLE
Metadata Template greyed out

### ISSUE THREAD

**Issue by HabiusRex** [kaiiiz/obsidian-raindrop-highlights-plugin#29]
Hello. Thanks for developing this plugin.
I am not a developer so knowledge is limited. 
In the settings for the plugin the metadata template is greyed out and I am unable to edit. The content template works and I have no issue.  Can you suggest a fix for this?

**Comment by kaiiiz** [comment]
The metadata template shouldn't be greyed out by default.

The only check this plugin will do is checking the rendered result of the metadata template is a valid YAML syntax. It is used to prevent the front matter corruption issue since this plugin relies on the `raindrop_id` and `raindrop_last_update` properties in the front matter. If your template is not a valid YAML syntax, the plugin will reject the update (the border will become red color).

Can you open your developer console in Obsidian and point to the `textarea` of the metadata template? If the `textarea` doesn't have `disabled` property, it should be editable.

![image](https://user-images.githubusercontent.com/30596812/206648491-d8ff491b-485e-4c6d-a91a-48a0a362af3f.png)

**Comment by HabiusRex** [comment]
Much appreciated. I'm not sure what I did but in the end I re-typed the default metadata template and it all works as expected. Cheers.

**Comment by jpfieber** [comment]
Mine was greyed out as well. I typed out the part that I wanted (tags) and it worked fine.
