### ISSUE TITLE
HTML entities appearing on sync

### ISSUE THREAD

**Issue by lnikj** [kaiiiz/obsidian-raindrop-highlights-plugin#62]
As far as I can tell, Raindrop is storing flat text/markdown.

I'm pulling the {{note}} field in, where I store long summaries.

Things like apostrophe's are being converted to &#39's in the Obsidian flle.  (ie text -> HTML).

Is this the plugin that is doing this, and is this preventable?

Thanks.

**Comment by kaiiiz** [comment]
Thanks for reporting the bug. I'll take a look on it later.

**Comment by kaiiiz** [comment]
I've checked this issue and I think it's the expected behavior. Nunjucks [autoescaping](https://mozilla.github.io/nunjucks/api.html#autoescaping) all output for security reason. You can use [safe](https://mozilla.github.io/nunjucks/templating.html#safe) filter in the template to disable the auto escape feature.

**Comment by kaiiiz** [comment]
Fixed in v0.0.19. A new option is added to disable autoescaping feature globally.
