### ISSUE TITLE
Sync Raindrop collection failed: Request failed with status code 429

### ISSUE THREAD

**Issue by dta0115** [kaiiiz/obsidian-raindrop-highlights-plugin#63]
Hi, 

I tried to import a collection of bookmarks to obsidian from raindrops. As soon as I got this error " Request failed with status code 429", I realized that I should not make a lot of import at once.
I have been having this error for a few days without adding any new bookmarks to the import collection, and sadly it is not getting resolved. Is there a solution?

**Comment by kaiiiz** [comment]
Is this still happening? Can you provide the error log in the develop console? Have you tried manually syncing using the command `Raindrop Highlights: Sync highlights` after taking a few minute' break? Thanks

**Comment by dta0115** [comment]
Hi Zheng,

Thank you for the reply.

I made a new folder in Raindrop and used that for the sync. Because all the
bookmarks from the previous sync are stored in Obsidian, I thought it would
not be a huge problem if I synced with a different folder from Raindrop.

I need help getting the error log in the develop console. Could you direct
me to the weblink with the instructions?

Yes, I tried manually syncing using the command. Since the start, I have
turned off the automatic sync and done manual syncing.

Bests,
Aman

**Comment by apricot13** [comment]
I'm also getting this issue,  https://developer.raindrop.io/#rate-limiting For context I have 7.3k bookmarks but only 187 highlights so it shouldn't timeout. 

It very quickly gets up to the max 120 and then the entire script fails.
<img width="236" alt="image" src="https://github.com/kaiiiz/obsidian-raindrop-highlights-plugin/assets/649148/106ace5c-164e-47cd-ad01-f536972b3d79">


also, I have only sync bookmarks with highlights selected but its still looking through everything. https://developer.raindrop.io/v1/highlights#get-all-highlights might be more useful when that box is checked.

**Comment by kaiiiz** [comment]
@apricot13 Thanks for the study on this issue. I think maybe a proper fix for this issue is to "wait" a small amount of time and retry several times before failing when we get the 429 response from Raindrop.

Besides, switching implementation to `https://api.raindrop.io/rest/v1/highlights` is not able to solve this issue. That said you have 7.3k bookmarks and 187 highlights, and each bookmark has only one highlight. The total requests needed in the current implementation is to request 7.3k / 50 ~= 146 pages of bookmarks. On the other hand, the new implementation requires ceil(187 / 50) + 187 ~= 191 requests since we still need to request the `https://api.raindrop.io/rest/v1/raindrop/{id}` endpoint to retrieve the bookmark data before template rendering.

BTW, I found that raindrop can support 50 bookmarks in a single page, and the current implementation is only using 25 bookmarks. Increasing the page size to 50 may help to eliminate this issue as well.

**Comment by kaiiiz** [comment]
Fixed in v0.0.19.

**Comment by apricot13** [comment]
Thanks @kaiiiz  I'll try running the import again with the new version  when I get a chance! I might even have a few more bookmarks for it by then! 😂
